
language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gicta/flowness -f Dockerfile .

#script:
#  - docker run gicta/flowness npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Happelz"
  env: "Happelz-env"
  bucket_name: "elasticbeanstalk-us-east-2-065243407389"
  bucket_path: "Happelz"
  on:
    branch: master
  access_key_id: $aws-access-key
  secret_access_key: "$aws-private-key"
